# Database Configuration Example
# Copy this file to your config directory and customize for your environment

database:
  # Backend selection: firestore, postgresql
  backend: postgresql
  
  # Connection settings
  host: localhost
  port: 5432
  database_name: chatcore
  username: ${DB_USERNAME}  # Set via environment variable
  password: ${DB_PASSWORD}  # Set via environment variable
  
  # Connection pool settings
  connection_pool_size: 10
  query_timeout: 30.0
  
  # Security settings
  use_ssl: true
  ssl_cert_path: null  # Path to SSL certificate if needed
  
  # Backend-specific configuration
  backend_config:
    schema: public  # PostgreSQL schema name
    # For Firestore, use:
    # project_id: your-gcp-project-id
    # credentials_path: /path/to/service-account.json

# Encryption configuration
encryption:
  # 32-character encryption key (set via environment variable)
  key: ${ENCRYPTION_KEY}
  
  # Fields that should be automatically encrypted
  sensitive_fields:
    - password
    - api_key
    - secret
    - token
    - ssn
    - social_security_number
    - credit_card
    - card_number
    - phone
    - address
    - personal_info

# Cache configuration (Redis)
cache:
  host: localhost
  port: 6379
  db: 0
  password: null  # Set if Redis requires authentication
  default_ttl: 300  # Default cache TTL in seconds (5 minutes)
  max_connections: 10
  socket_timeout: 5.0
  socket_connect_timeout: 5.0
  
  # Cache strategy settings
  enable_query_cache: true
  enable_record_cache: true
  cache_large_results: false  # Don't cache results > 1MB
  max_cache_size_mb: 1  # Maximum size per cache entry

# Audit logging configuration
audit:
  log_level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  enable_console: true
  enable_file: true
  log_file: logs/database_audit.log
  
  # Audit buffer settings
  buffer_size: 100  # Number of events to buffer before writing
  flush_interval: 30  # Seconds between forced flushes
  
  # Log rotation
  max_file_size_mb: 100
  backup_count: 5
  
  # What to log
  log_operations: true
  log_queries: true
  log_security_events: true
  log_performance_metrics: true
  
  # Performance thresholds
  slow_query_threshold_ms: 1000  # Log queries slower than this
  
# Environment-specific overrides
development:
  database:
    connection_pool_size: 5
    query_timeout: 60.0
  cache:
    default_ttl: 60  # Shorter cache in development
  audit:
    log_level: DEBUG
    enable_console: true

production:
  database:
    connection_pool_size: 20
    query_timeout: 30.0
    use_ssl: true
  cache:
    default_ttl: 600  # Longer cache in production
    max_connections: 50
  audit:
    log_level: INFO
    enable_console: false
    enable_file: true

testing:
  database:
    backend: mock  # Use mock database for testing
    database_name: test_db
  cache:
    host: localhost
    db: 1  # Use different Redis DB for tests
  audit:
    log_level: ERROR  # Minimal logging in tests
    enable_console: false
    enable_file: false
