# GDPR Compliance Rules
gdpr:
  data_processing_agreement_url: "https://example.com/data_processing_agreement"
  user_rights_information_url: "https://example.com/user_rights"
  privacy_policy_url: "https://example.com/privacy_policy"
  require_explicit_consent: true
  consent_log_retention_days: 365  # How long to keep records of consent (e.g., 1 year)

# Session Management
session:
  expiration_policy: "inactivity"  # Options: "inactivity", "absolute", "sliding"
  inactivity_timeout_minutes: 30  # Session expires after 30 minutes of inactivity
  absolute_timeout_days: 30  # Session expires after 30 days regardless of activity
  sliding_timeout_minutes: 60  # Session expiration extended by 60 minutes of activity
  automatic_session_renewal: true

# Logging Preferences
logging:
  enabled: true
  log_level: "INFO"  # Options: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
  log_directory: "logs"
  log_file_retention_days: 90
  sensitive_data_masking: true #Mask PII from logs.

# Encryption Settings
encryption:
  enabled: true
  data_at_rest_encryption: true
  data_in_transit_encryption: true
  encryption_algorithm: "AES-256" #AES is generally a good choice

# Consent Tracking
consent:
  enabled: true
  methods: ["explicit", "implied"] #Acceptable consent types
  explicit_consent_text: "I agree to the terms and conditions"
  implied_consent_acceptance_duration_seconds: 5  #Consider a user to have given consent if they use the service for this long

# Data Retention Policy
data_retention:
  chat_history_retention_days: 365  # Retain chat history for 1 year
  user_profile_retention_days: 730  # Retain user profiles for 2 years
  transaction_data_retention_days: 1095 #Retain transaction data for 3 years
  anonymization_policy: "pseudonymization" #Options: "pseudonymization", "deletion", "aggregation"
  anonymization_delay_days: 30 #Time after retention period to anonymize data.

# Anonymization settings (if enabled)
anonymization:
  pseudonymization:
    salt: "unique_salt_value" #Salt for generating pseudonyms

# Audit Logging
audit_logging:
  enabled: true
  log_retention_days: 180
  logged_events: ["user_login", "data_access", "data_modification", "consent_change"] #List of events to log





# GDPR Compliance: Defines URLs for important GDPR-related information, enables explicit consent, and sets a retention period for consent logs.
# Session Management: Configures session expiration policies (inactivity, absolute, sliding), timeout values, and automatic session renewal.
# Logging Preferences: Enables logging, sets the log level, specifies the log directory, configures log file retention, and enables sensitive data masking.
# Encryption Settings: Toggles encryption for data at rest and in transit, and specifies the encryption algorithm.
# Consent Tracking: Enables consent tracking, defines acceptable consent methods (explicit, implied), provides explicit consent text, and sets a duration for implied consent acceptance.
# Data Retention Policy: Defines retention periods for different types of data (chat history, user profiles, transaction data), specifies an anonymization policy, and sets an anonymization delay.
# Anonymization Settings: Configure pseudonymization with a salt value for generating pseudonyms.
# Audit Logging: Enables audit logging, sets a log retention period, and defines a list of events to log.